// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yeynvjctkjmnrtukakum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlleW52amN0a2ptbnJ0dWtha3VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTIwOTIsImV4cCI6MjA3MDIyODA5Mn0.v3IpNWOGZTxWHx8O19k4muNfZX7ozsMMxnz-IxwlPbA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});